id = "html-django"
name = "HTML-Django Template Support"
version = "1.0.0"
schema_version = 1
description = "Highlighting for HTML-Django templates."
authors = ["Serdar Akarca"]
repository = "https://github.com/akarca/html-jinja"

[grammars.jinja]
repository = "https://github.com/cathaysia/tree-sitter-jinja"
path = "tree-sitter-jinja"
commit = "07a62adf99c0f41e0cab7ab523541309a8d73dc4"

[grammars.html]
repository = "https://github.com/JaagupAverin/tree-sitter-html"
commit = "5f47d6608069f4ef35d836dc0083c90733c72810"
